# CountVectorizer, TfidfVectorizer, HashingVectorizer

The text must be parsed to remove words, called tokenization. Then the words need to be encoded as integers 
or floating point values for use as input to a machine learning algorithm, called feature extraction 
(or vectorization).

The scikit-learn library offers easy-to-use tools to perform both tokenization and feature extraction of 
your text data.

In [5]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

# CountVectorizer

The CountVectorizer provides a simple way to both tokenize a collection of text documents and build a 
vocabulary of known words, but also to encode new documents using that vocabulary.

In [17]:
text = ["The quick brown fox jumped over the lazy dog."]
cv = CountVectorizer()
cv.fit(text)
vector_text = cv.transform(text)


print('The vocabulary is :\n', cv.vocabulary_)
print('The Shape of the vector text is :\n', vector_text.shape)
print('The type of the vector text is :\n', type(vector_text))
print('Array of the vector text is :\n',vector_text.toarray())

The vocabulary is :
 {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
The Shape of the vector text is :
 (1, 8)
The type of the vector text is :
 <class 'scipy.sparse.csr.csr_matrix'>
Array of the vector text is :
 [[1 1 1 1 1 1 1 2]]


for every unique word CountVectorizer takes 1. Sometimes a specific word stay more than one time in a sentence 
in this situation CountVectorixer takes number based on the word number. Suppose, The word stay two time in a sence 
CountVectorizer will take 2 for two the. 

In [ ]:
#Another Example of CountVectorizer

In [40]:
text2 = ['This is the first document.',
         'This document is the second document.',
         'And this is the third one.',
         'Is this the first document?']

cv.fit(text2)
vectorizer_text = cv.transform(text2)
print('The vocabulary is :\n', cv.vocabulary_)
print('The Shape of the vector text is :\n', vectorizer_text.shape)
print('The type of the vector text is :\n', type(vectorizer_text))
print('Array of the vector text is :\n',vectorizer_text.toarray())


The vocabulary is :
 {'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
The Shape of the vector text is :
 (4, 9)
The type of the vector text is :
 <class 'scipy.sparse.csr.csr_matrix'>
Array of the vector text is :
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [44]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
vec_text = vectorizer2.fit_transform(text2)

print(vectorizer2.get_feature_names())
print('Array of the vector text is :\n',vec_text.toarray())

['and this', 'document is', 'first document', 'is the', 'is this', 'second document', 'the first', 'the second', 'the third', 'third one', 'this document', 'this is', 'this the']
Array of the vector text is :
 [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


a parameter  ngram_range=(2,2) means every time take two word in one column.

# TfidfVectorizer

One issue with simple counts is that some words like “the” will appear many times and their large counts will
not be very meaningful in the encoded vectors.

An alternative is to calculate word frequencies, and by far the most popular method is called TF-IDF. This is an acronym than stands for “Term Frequency – Inverse Document” Frequency which are the components of the 
resulting scores assigned to each word.

In [26]:
tv = TfidfVectorizer()
tv.fit(text)
vector_text = tv.transform(text)

print('The vocabulary of tv is :\n',tv.vocabulary_)
print('Shape of vector_text is :\n',vector_text.shape)
print('Type of vector text is :\n',type(vector_text))
print('Array of the vector text is :\n',vector_text.toarray())

The vocabulary of tv is :
 {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
Shape of vector_text is :
 (1, 8)
Type of vector text is :
 <class 'scipy.sparse.csr.csr_matrix'>
Array of the vector text is :
 [[0.30151134 0.30151134 0.30151134 0.30151134 0.30151134 0.30151134
  0.30151134 0.60302269]]


In [ ]:
TfidfVectorizer takes frequency based on the number of word on text. If a word stay two time in a text, this word
will take more frequency 

In [ ]:
#Another Example

In [47]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]

vector_text = tv.fit_transform(corpus)


print('Name of the vector is :\n', tv.get_feature_names())
print('Shape of the vector is :\n', vector_text.shape)
print('Array of the vector is :\n', vector_text.toarray())

Name of the vector is :
 ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
Shape of the vector is :
 (4, 9)
Array of the vector is :
 [[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


# HashingVectorizer

Counts and frequencies can be very useful, but one limitation of these methods is that the vocabulary can become very large.

This, in turn, will require large vectors for encoding documents and impose large requirements on memory and slow down algorithms.

A clever work around is to use a one way hash of words to convert them to integers. The clever part is that no vocabulary is required and you can choose an arbitrary-long fixed length vector. A downside is that the hash is a one-way function so there  is no way to convert the encoding back to a word (which may not matter for many supervised learning tasks).

The HashingVectorizer class implements this approach that can be used to consistently hash words, then tokenize and encode documents as needed.

In [35]:
hv = HashingVectorizer(n_features=20)
hv.fit(text)
vector_hv = hv.transform(text)

print("shape of the vector :\n", vector_hv.shape)
print('Type of the vector_hv is :',type(vector_hv))
print('array of the vector_hv is :',vector_hv.toarray())

shape of the vector :
 (1, 20)
Type of the vector_hv is : <class 'scipy.sparse.csr.csr_matrix'>
array of the vector_hv is : [[ 0.          0.          0.          0.          0.          0.33333333
   0.         -0.33333333  0.33333333  0.          0.          0.33333333
   0.          0.          0.         -0.33333333  0.          0.
  -0.66666667  0.        ]]


HashingVectorizer reduce the number of feature that is very helpful for algorithm. 

In [48]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]

vector_hv = hv.fit_transform(corpus)

print('Shape of the vector_hv is :\n',vector_hv.shape)
print('Array of the vector is :\n', vector_hv.toarray())


Shape of the vector_hv is :
 (4, 20)
Array of the vector is :
 [[ 0.          0.          0.4472136   0.          0.          0.
   0.          0.          0.          0.          0.          0.
  -0.4472136   0.          0.          0.         -0.4472136   0.4472136
  -0.4472136   0.        ]
 [ 0.          0.          0.35355339  0.          0.          0.
   0.          0.          0.          0.          0.          0.
  -0.70710678  0.          0.          0.35355339  0.          0.35355339
  -0.35355339  0.        ]
 [ 0.          0.40824829  0.40824829  0.         -0.40824829 -0.40824829
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.40824829
  -0.40824829  0.        ]
 [ 0.          0.          0.4472136   0.          0.          0.
   0.          0.          0.          0.          0.          0.
  -0.4472136   0.          0.          0.         -0.4472136   0.4472136
  -0.4472136   0.        ]