In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
data = pd.read_csv('/home/hasan/Desktop/DATA_SET/Machine_Learning-basic-dataset/3 insurance.csv')

In [4]:
data.head()

age  insurance
0   22          0
1   34          1
2   27          0
3   37          0
4   45          1

In [5]:
Xtrain,xtest, Ytrain,ytest = train_test_split(data[['age']], data.insurance)

In [6]:
xtest

age
1    34
22   32
10   76
19   56
17   63
11   34
15   45

In [7]:
LR = LogisticRegression()
LR.fit(Xtrain,Ytrain)

/home/hasan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
LR.predict(xtest)

array([1, 1, 1, 1, 1, 1, 1])

In [9]:
LR.score(xtest,ytest)

0.7142857142857143

In [10]:
LR.predict_proba(xtest)

array([[0.40987285, 0.59012715],
       [0.43307884, 0.56692116],
       [0.08599921, 0.91400079],
       [0.19598379, 0.80401621],
       [0.14871003, 0.85128997],
       [0.40987285, 0.59012715],
       [0.29151462, 0.70848538]])

In [11]:
LR.predict([[50]])

array([1])

In [12]:
LR.predict([[18]])

array([0])