In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
email = pd.read_csv('/home/hasan/Desktop/DATA_SET/spam.csv')

In [3]:
emails = email.loc[:,['v1','v2']]

In [4]:
emails.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
emails.rename(columns={'v1':'category', 'v2':'message'}, inplace=True)

In [6]:
emails.shape

(5570, 2)

In [7]:
emails.groupby('category').describe()

message                                                            \
           count unique                                                top   
category                                                                     
ham         4823   4509                             Sorry, I'll call later   
spam         746    653  Please call our customer service representativ...   

               
         freq  
category       
ham        30  
spam        4

In [8]:
emails['spam'] = emails['category'].apply(lambda x:1 if x=='spam' else 0)

In [9]:
emails.head()

category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
emails.isnull().sum()

category    0
message     1
spam        0
dtype: int64

In [11]:
emails['message'].fillna(method='ffill', inplace=True)

In [12]:
Xtrain,xtest, Ytrain,ytest = train_test_split(emails.message, emails.spam, test_size=0.25)

In [13]:
v = CountVectorizer()

x_train_count = v.fit_transform(Xtrain.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
MNB = MultinomialNB()

MNB.fit(x_train_count, Ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [15]:
count_xtest = v.transform(xtest)
MNB.predict(count_xtest)

array([1, 0, 0, ..., 0, 0, 0])

In [16]:
MNB.score(count_xtest, ytest)

0.9820531227566404

In [17]:
New_emails = ['Hey Hasan what about your exam','I am not very fine because my exam is running for this I always stay busy and fearer']

In [18]:
test = v.transform(New_emails)

MNB.predict(test)

array([0, 0])